---
title: "r-matrices"
format: html
---
## create matrices in R

```{r}
# create sequence of values ----
my_values <- seq(from = 1, to = 10, by = 1)
my_values

# convert to matrix ----

my_matrix <- matrix(data = my_values, 
                   nrow = 2,
                   ncol = 5,
                   byrow = TRUE)

class(my_matrix)

# if we want to update the default setting to have the values go into the matrix by row instead of by column, change "byrow" to TRUE  ----

```

## incorrectly declared matrix sizes 
```{r}
matrix(data = my_values, nrow = 2, ncol = 3, byrow = TRUE)
matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)

# the nrow and ncol affects the way our vectors are put into matrix
```
```{r}
# scalar multiplication ---- 
4 * my_matrix

# let's create a second matrix ----
my_values2 <- seq(from = 21, to = 30, by. = 1)
my_matrix2 <- matrix(data = my_values2, nrow = 2, byrow = TRUE)

# don't need to specify the cols above because in this specific case we have two rows that we want, and since we have 10 values and two rows, and r must distribute the values equally in the two rows, it has no option but to create 5 cols. 5 * 2 = 10 ----

# add matrices ---- 
my_matrix + my_matrix2 

# sub matrices ----
my_matrix2 - my_matrix

# multiplying (dot product) of matrices ----

my_matrix * my_matrix2

```
```{r}
# make a couple of 2x2 matrices ----
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)
cats
dogs

cats %*% dogs 

```

## Leslie Matrix 

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08,0),
                        nrow = 3,
                        ncol = 3,
                        byrow = TRUE)

insect_leslie

# initial starting conditions ----

insect_y0 <- c(12000, 700, 500)

# you cannot start the naming of a varible w a number, must start w a character. ----

# pop at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0

insect_y1 

# pop at year 2
insect_y2 <- insect_leslie %*% insect_y1

insect_y2

insect_y3 <- insect_leslie %*% insect_y2

insect_y3

insect_y4 <- insect_leslie %*% insect_y3

insect_y4

```
## Tree Leslie example
```{r}
# make matrix ----
tree_leslie <- matrix(data = c(0, 0 , 5000, 0.1, 0 , 0 , 0 , 0.06, 0.95), 
                      nrow = 3, 
                      ncol = 3, 
                      byrow = TRUE)
tree_leslie

# initial starting conditions ----
tree_y0 <- c(5000, 0, 0)

# pop at year 1 ----
tree_y1 <- tree_leslie %*% tree_y0
tree_y1

tree_y2 <- tree_leslie %*% tree_y1
tree_y2

tree_y3 <- tree_leslie %*% tree_y2
tree_y3

```







